#!/bin/bash
# export-docs.sh -- regenerate docs/ (the published docs) from the private
# working notes in .agent/, replacing addresses, paths and names with
# placeholders and dropping links to private-only files. Run before committing.
set -euo pipefail
ROOT="$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)"
cd "$ROOT"
[ -d .agent ] || { echo "no .agent/ notes here; docs/ is already the published copy" >&2; exit 0; }
mkdir -p docs
declare -A MAP=(
	[.agent/System/project_architecture.md]=architecture.md
	[.agent/System/cast-pipeline.md]=cast-pipeline.md
	[.agent/System/tv-desktop.md]=tv-desktop.md
	[.agent/System/hardware-and-platform.md]=hardware-and-platform.md
	[.agent/System/configuration-reference.md]=configuration-reference.md
	[.agent/SOP/casting-operations.md]=operating-and-debugging.md
	[.agent/SOP/rebuilding-patched-deps.md]=rebuilding-patched-senders.md
)
for src in "${!MAP[@]}"; do
	python3 - "$src" "docs/${MAP[$src]}" <<'PY'
import re, sys
src, dst = sys.argv[1], sys.argv[2]
s = open(src).read()
# Private substitutions (addresses, paths, names -> placeholders) live in
# .agent/export-scrub.json, which is not published.
import json
scrub = json.load(open(".agent/export-scrub.json"))
subs = scrub["substitutions"]
for a, b in subs:
    s = re.sub(a, b, s)
# Links between published docs -> their new names; links to private files -> text.
ren = {"project_architecture.md": "architecture.md", "casting-operations.md": "operating-and-debugging.md",
       "rebuilding-patched-deps.md": "rebuilding-patched-senders.md"}
def link(m):
    text, target = m.group(1), m.group(2)
    path, _, anchor = target.partition("#")
    name = path.split("/")[-1]
    if not path.endswith(".md") or path.startswith("http"):
        return m.group(0)
    published = {"architecture.md", "cast-pipeline.md", "tv-desktop.md", "hardware-and-platform.md",
                 "configuration-reference.md", "operating-and-debugging.md", "rebuilding-patched-senders.md"}
    name = ren.get(name, name)
    if name in published:
        return f"[{text}]({name}{'#' + anchor if anchor else ''})"
    return text
s = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", link, s)
s = "<!-- Generated by scripts/export-docs.sh; edit the source notes, not this file. -->\n" + s
open(dst, "w").write(s)
PY
done
echo "docs/: $(ls docs | tr '\n' ' ')"
forbidden=$(python3 -c 'import json; print(json.load(open(".agent/export-scrub.json"))["forbidden"])')
if grep -rniE "$forbidden" docs/; then
	echo "export-docs: private strings left in docs/ (above)" >&2; exit 1
fi
echo "privacy check: clean"
